### ISSUE TITLE
Please clarify

### ISSUE THREAD

**Issue by RobertAJMarshall** [ZoranStojsavljevic/lava-server-vm#1]
You say don't use vagrant 2.1.2 and use 2.1.1 instead but don't give any reasons for that preference. It would be clearer if you outlined the (presumed) bug which leads you to this? Is it the vagrant ssh issue you described in an email?

**Comment by ZoranStojsavljevic** [comment]
Robert,

I have fatal errors if I use Vagrant 2.1.2 with VBox 5.2.14 (also included VBox extension pack). My script importbox,sh (which has lot of logic in there) fatally fails. It drove me crazy, since I have upgraded VBox and extensions from 5.2.12 to latest and greatest 5.2.14 blindly. It took me two+ hours to found the issue.

So, once I downgraded Vagrant 2,1,2 to 2.1.1, everything worked like a charm. Maybe this is only me... But I do NOT like Vagrant, since Vagrant taps to VBox config files and starts changing VBox environment.

I verified this with Vbox admin Socratis (Vbox.org forum). Long time ago (6+ months ago). Socratis wanted to delete my posts about Vagrant + VBox (I somehow prevented this, promised that I never will bring Vagrant mess with VBox on forum). It is forbidden to talk on VBox forum about Vagrant+VBox use.

You can try to do the verification yourself. Please, do so.

Zoran
